/**
 * 手动补充的招股数据（全球发售章程 / 媒体报道 / AI 分析）
 * PHIP 无法解析的字段（基石名单、招股日程、孖展等）在此维护
 * 合并时优先于 PHIP 中的「待披露」占位
 */

/** @type {Record<number, object>} */
const OFFERING_OVERRIDES = {
  108430: {
    status: '招股中',
    subscriptionPeriod: { start: '2026-05-28', end: '2026-06-02 12:00' },
    pricingDate: '2026-06-04',
    listingDate: '2026-06-05',
    darkPoolDate: '2026-06-04',
    allocationMechanism: '机制B',
    publicOfferRatio: '10%（固定）',
    internationalOfferRatio: '90%',
    clawback: {
      enabled: false,
      description: '机制B选定固定10%公开发售，无强制回拨',
      tiers: [],
    },
    offerPriceRange: { low: 66.4, high: 66.4, currency: 'HKD', note: '上限定价 66.40 港元' },
    finalOfferPrice: '66.40 HKD（待定价日确认）',
    lotSize: 100,
    entryFee: '6,706.97 HKD',
    hammerMaxLots: '86,966 手（公开可供认购）',
    sharesOffered: '8,696.58 万股 H 股',
    overAllotmentShares: '1,304.48 万股（15% 超额配股权）',
    issuanceRatio: '12.00%（占扩大后股本）',
    totalFundraising: '最高约 57.75 亿 HKD',
    netProceeds: '约 56.17 亿 HKD',
    marketCapRange: '最高约 481.21 亿 HKD',
    hShareMarketCap: '约 57.75 亿 HKD（H 股部分）',
    greenShoe: {
      hasGreenShoe: true,
      ratio: '15%',
      shares: '1,304.48 万股',
      amount: '约 8.66 亿 HKD',
      stabilizingManager: '华泰金融控股 / 招商证券（香港）',
    },
    cornerstone: {
      hasCornerstone: true,
      investors: [
        { name: 'GIC Private Limited（新加坡政府投资公司）', amount: '8,000 万美元', tier: 'sovereign', note: '最大基石' },
        { name: '泰康人寿', amount: '3,000 万美元', tier: 'well_known', note: '' },
        { name: 'Pinpoint Asset Management', amount: '3,000 万美元', tier: 'top_tier', note: '' },
        { name: 'UBS AM Singapore', amount: '3,000 万美元', tier: 'top_tier', note: '' },
        { name: '工银理财', amount: '2,000 万美元', tier: 'well_known', note: '' },
        { name: 'Marshall Wace Asia (MWAL)', amount: '2,000 万美元', tier: 'top_tier', note: '' },
        { name: 'Millennium', amount: '2,000 万美元', tier: 'top_tier', note: '' },
        { name: '高瓴 HHLRA / HIM', amount: '未分项披露', tier: 'top_tier', note: '' },
        { name: 'CPE Juniper', amount: '未分项披露', tier: 'top_tier', note: '' },
        { name: 'Eastspring（新加坡+香港）', amount: '未分项披露', tier: 'top_tier', note: '' },
        { name: '中邮理财', amount: '未分项披露', tier: 'well_known', note: '' },
        { name: '富国基金 / 富国香港', amount: '未分项披露', tier: 'well_known', note: '' },
        { name: '保诚 Prudential', amount: '未分项披露', tier: 'well_known', note: '' },
      ],
      totalAmount: '3.58 亿美元（约 28.03 亿 HKD）',
      totalRatio: '48.54%（占全球发售；超额配股权悉数行使后 36.71%）',
      postIpoRatio: '占已发行股本约 5.61%-5.83%',
      authorityAssessment: '权威 — 含 GIC 主权基金、高瓴、瑞银资管、泰康、Millennium 等 13 家全球顶级长线机构，阵容豪华',
      lockUpPeriod: '上市日起 6 个月',
    },
    overallCoordinator: '华泰国际、招商证券国际（联席保荐人）',
    underwriters: ['华泰国际', '招商证券国际'],
    oversubscription: {
      public: '首日已足额（截至 5/28 17:00）',
      marginTotal: '孖展约 29.52 亿 HKD',
      marginMultiple: '约 5.11 倍',
    },
    useOfProceeds: '55% 深远海综合解决方案；20% 欧洲总装基地；10% 全球研发中心；5% 海外拓展；10% 营运资金',
    volumeAdjustment: '15% 发售量调整权',
    oldSharesOffered: false,
    notes: ['A+H 同源标的', '基石近五成，锁定期 6 个月托底明显', 'A/H折价见 ahSpread 实时计算'],
  },

  107901: {
    status: '招股中',
    subscriptionPeriod: { start: '2026-05-28', end: '2026-06-02 12:00' },
    pricingDate: '2026-06-04',
    listingDate: '2026-06-05',
    darkPoolDate: '2026-06-04',
    allocationMechanism: '机制A（默认）',
    publicOfferRatio: '10%（初始）',
    internationalOfferRatio: '90%',
    clawback: {
      enabled: true,
      description: '超额认购触发回拨，上限取决于所选方案（新规：方案一最高 35% 或方案二最高 60%）',
      tiers: [
        { threshold: '≥15 倍', ratio: '回拨至 30%' },
        { threshold: '≥50 倍', ratio: '回拨至 40%' },
        { threshold: '≥100 倍', ratio: '回拨至 50%' },
      ],
    },
    offerPriceRange: { low: 5.18, high: 6.38, currency: 'HKD' },
    finalOfferPrice: '待定价（中位数参考 5.78 HKD）',
    lotSize: 500,
    entryFee: '3,222.17 HKD',
    hammerMaxLots: '12,500 手（顶头槌，按中位价计约 322,217 HKD）',
    sharesOffered: '1.25 亿股',
    overAllotmentShares: '1,875 万股（15% 超额配股权）',
    totalFundraising: '最多约 7.98 亿 HKD',
    netProceeds: '约 6.72 亿 HKD（按中位价 5.78 计）',
    marketCapRange: '约 25.9 - 31.9 亿 HKD',
    hShareMarketCap: '同总市值（纯 H 股上市）',
    greenShoe: {
      hasGreenShoe: true,
      ratio: '15%',
      shares: '1,875 万股',
      amount: '约 1.08 亿 HKD（中位价）',
      stabilizingManager: '星展亚洲融资',
    },
    cornerstone: {
      hasCornerstone: false,
      investors: [],
      totalAmount: '无',
      totalRatio: '0%',
      authorityAssessment: '无基石 — 公司称前期推广反应不俗，未感担忧；但缺少长线资金托底',
      lockUpPeriod: 'N/A',
    },
    overallCoordinator: '星展亚洲融资（独家保荐人）',
    underwriters: ['星展亚洲', '招银国际', '辉立', '浦银国际', 'uSmart'],
    oversubscription: { public: '招股中', marginTotal: '待更新', marginMultiple: '待更新' },
    useOfProceeds: '36.6% 扩店/线上线下；20% 还贷；15% 并购；11.4% IT；3.5% 品牌；3.5% 供应链；10% 营运资金',
    notes: ['港股药妆第一股', '无基石投资者需关注首日抛压'],
  },

  108250: {
    status: '招股中',
    subscriptionPeriod: { start: '2026-05-28', end: '2026-06-02 12:00' },
    pricingDate: '2026-06-03',
    listingDate: '2026-06-05',
    darkPoolDate: '2026-06-04',
    allocationMechanism: '机制A（默认）',
    offerPriceRange: { low: 96.06, high: 96.06, currency: 'HKD', note: '固定发售价' },
    finalOfferPrice: '96.06 HKD',
    lotSize: 50,
    entryFee: '4,851.44 HKD',
    sharesOffered: '1,419.32 万股 H 股',
    totalFundraising: '约 13.63 亿 HKD',
    netProceeds: '约 12.55 亿 HKD',
    marketCapRange: '约 125 亿 HKD（按发售价）',
    greenShoe: {
      hasGreenShoe: true,
      ratio: '15%',
      shares: '约 213 万股',
      amount: '约 2.05 亿 HKD',
      stabilizingManager: '国金证券（香港）',
    },
    cornerstone: {
      hasCornerstone: true,
      investors: [
        { name: 'OrbiMed Funds', amount: '领投', tier: 'top_tier', note: '全球顶级 biotech VC' },
        { name: 'TruMed Funds', amount: '未分项', tier: 'top_tier', note: '' },
        { name: '华泰资本投资及最终客户', amount: '未分项', tier: 'well_known', note: '' },
        { name: '睿远基金', amount: '未分项', tier: 'well_known', note: '' },
        { name: '富国基金 / 富国香港', amount: '未分项', tier: 'well_known', note: '' },
        { name: '惠理 Fundsmith', amount: '未分项', tier: 'top_tier', note: '' },
        { name: 'GBAHIL', amount: '未分项', tier: 'general', note: '' },
        { name: 'FRM / 源峰远景成长基金', amount: '未分项', tier: 'top_tier', note: '' },
        { name: '中国银河国际投资', amount: '未分项', tier: 'well_known', note: '' },
      ],
      totalAmount: '8,700 万美元（约 6.81 亿 HKD）',
      totalRatio: '49.96%（709.04 万股）',
      authorityAssessment: '较权威 — OrbiMed 领投 biotech 专业度高，叠加华泰、富国、惠理、银河等，18A 阵容中上',
      lockUpPeriod: '标准基石锁定期（通常 6 个月）',
    },
    overallCoordinator: '国金证券（香港）（独家保荐人）',
    underwriters: ['国金证券', '广发证券（香港）', '农银国际', '建银国际', '山证国际'],
    notes: ['18A 未盈利生物科技公司', '固定发行价 96.06 港元'],
  },

  108337: {
    status: '招股已结束',
    subscriptionPeriod: { start: '2026-05-26', end: '2026-05-29 12:00' },
    pricingDate: '2026-06-02',
    listingDate: '2026-06-03',
    darkPoolDate: '2026-06-02 16:15-18:30',
    allocationMechanism: '机制B',
    offerPriceRange: { low: 14.6, high: 17.1, currency: 'HKD' },
    finalOfferPrice: '待公布（中位数参考 15.85 HKD）',
    lotSize: 200,
    entryFee: '3,454.49 HKD',
    sharesOffered: '4,000 万股 H 股',
    totalFundraising: '最高约 6.84 亿 HKD',
    netProceeds: '约 5.33 亿 HKD（中位价）',
    marketCapRange: '58.4 - 68.4 亿 HKD',
    greenShoe: { hasGreenShoe: true, ratio: '15%', shares: '600 万股', stabilizingManager: '越秀证券' },
    cornerstone: {
      hasCornerstone: false,
      investors: [],
      totalAmount: '无',
      totalRatio: '0%',
      authorityAssessment: '无基石 — 机制 B + 无基石，历史上部分类似结构波动较大；上市过程三进宫',
      lockUpPeriod: 'N/A',
    },
    overallCoordinator: '越秀融资（独家保荐人）',
    oversubscription: {
      public: '招股结束时',
      marginTotal: '孖展约 2.64 亿 HKD',
      marginMultiple: '约 3.85 倍',
    },
    useOfProceeds: '24.5% 河北首朗二期；24.8% 包头 SAF；15.7% 研发；14.6% 技改；9.7% 新产品；4.3% 投资；6.4% 营运资金',
    notes: ['港股 CCUS 第一股', '曾两度延期上市（诉讼纠纷）'],
  },

  108265: {
    overallCoordinator: '中金公司、国泰君安国际（联席保荐人）',
    underwriters: ['中金', '国泰君安国际'],
    useOfProceeds: '扩大 TPMS/BMS 商业化、研发、销售网络、战略收购、营运资金',
    marketCapRange: '预计 30-50 亿 RMB',
    notes: ['已通过聆讯，PHIP 登载 2026-05-10', '尚未启动招股'],
  },

  108561: {
    listingDate: '必须在 2026-06-30 前（对赌 deadline）',
    overallCoordinator: '中信证券、国元国际（联席保荐人）',
    marketCapRange: '预计 25-33 亿 RMB（PE 14-18x）',
    notes: ['对赌 deadline 2026-06-30', '七年第四次冲击 IPO', 'D 轮估值 22 亿 RMB'],
  },

  108528: {
    marketCapRange: '预计 30-45 亿 RMB（C2 轮 27 亿）',
    notes: ['18C 预商业化（-B）', '2026-05-29 通过聆讯', '对赌协议 IPO 失败自动恢复'],
  },
};

module.exports = { OFFERING_OVERRIDES };
